meta_product_name: "Give me a hand"
meta_title: "Give me a hand - Whit a friend's help, nothing is impossible!"
meta_description: "There's a lot to consider when moving overseas. Need of health insurance? What identity documents will you need to apply for? Where will you live and work? We've been there, and we get it! That's why we've got friends that can provide you with an answer to your questions and accompany you along the hard process of moving abroad."
meta_image: "friendshands.jpg" # should exist in `app/assets/images/`
